version: "3.8"
services:
  postgres:
    container_name: postgres-postgresql
    image: "postgres:13.0"
    command: postgres -c 'max_connections=950' -c 'log_statement=all'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    stdin_open: true
    tty: true

volumes:
  postgres-data:
